name: Run release-please
on:
  push:
    branches:
      - development
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: GoogleCloudPlatform/release-please-action@v3
        with:
          token: ${{ secrets.RELEASE_PR_TOKEN }}
          release-type: simple
